apiVersion: apps/v1
kind: Deployment
metadata:
 name: pet-shop-finances
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pet-shop-finances
  template:
    metadata:
     labels:
      app: pet-shop-finances
    spec:
      containers:
       - name: pet-shop-finances
         image: breno500as/pet-shop-finances:v2
         ports:
          - name: http
            containerPort: 8082
         livenessProbe:
            httpGet:
             path: /financa/actuator/health
             port: http
            timeoutSeconds: 100
            initialDelaySeconds: 100
            periodSeconds: 10         
         readinessProbe:
            httpGet:
              path: /financa/actuator/health
              port: http
            timeoutSeconds: 100
            initialDelaySeconds: 100
            periodSeconds: 10
          