apiVersion: apps/v1
kind: Deployment
metadata:
 name: pet-shop-finances
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pet-shop-finances
  template:
    metadata:
     labels:
      app: pet-shop-finances
    spec:
      containers:
       - name: pet-shop-finances
         image: pet-shop-finances:v1
         ports:
          - name: ps-fin-port
            containerPort: 8082
         livenessProbe:
            httpGet:
             path: /financa/actuator/health
             port: ps-fin-port
            timeoutSeconds: 100
            initialDelaySeconds: 100
            periodSeconds: 10         
         readnessProbe:
            httGet:
              path: /financa/actuator/health
              port: ps-fin-port
            timeoutSeconds: 100
            initialDelaySeconds: 100
            periodSeconds: 10
          