apiVersion: apps/v1
kind: Deployment
metadata:
 name: pet-shop-finances
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pet-shop-finances
  template:
    metadata:
     labels:
      app: pet-shop-finances
    spec:
      containers:
       - name: pet-shop-finances
         image: breno500as/pet-shop-finances:v2
         ports:
          - name: http
            containerPort: 8082
         livenessProbe:
            httpGet:
             path: /financa/actuator/health
             port: http
            timeoutSeconds: 100
            initialDelaySeconds: 100
            periodSeconds: 10         
         readinessProbe:
            httpGet:
              path: /financa/actuator/health
              port: http
            timeoutSeconds: 100
            initialDelaySeconds: 100
            periodSeconds: 10
         resources: #requisição de 10% da cpu
          requests:
            cpu: 200m
---

#Escalabilidade horizontal automática
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pet-shop-finances-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pet-shop-finances
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 5
          
#Testando a escalabilidade horizontal fazendo um loop infinito no servidor
#while true; do wget -q -O- --header "Authorization: Bearer eyJraWQiOiJwZXQtc2hvcC1zZWN1cml0eUBpc3Rpby1wZXQtc2hvcC1zZWN1cml0eS5oZXJva3VhcHAuY29tIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJwZXQtc2hvcC1zZWN1cml0eUBpc3Rpby1wZXQtc2hvcC1zZWN1cml0eS5oZXJva3VhcHAuY29tIiwiaXNzIjoicGV0LXNob3Atc2VjdXJpdHlAaXN0aW8tcGV0LXNob3Atc2VjdXJpdHkuaGVyb2t1YXBwLmNvbSIsImV4cCI6MTYwMjM4OTcyNiwibG9naW4iOiJicmVubyIsImlhdCI6MTYwMjM4NjEyNn0.kfmauBJDUga-X7BUOAzJeWq7tItJrTorv3QZRTW3pkIRp6G0rBhYZxCSwsM9AqFIUeadaNpgZ36jqW7awzOKJw3Mv3mcuJhSkYolGbMMIX2mpbISfSGjgXpTGTGdFEh854i5bSdejLKNQUWLf-5QCQFtp65Ec4HKLJ1m7J4D7RtPJnM35eYH6zm5OCPFPWyl9SJjQtmYFS0qqUzOEnWJmVgq6ot4HF76y_l3iVj7DuOVLMAYCh5dJARVvtfLvVV7j_AO24hXKvEMc4437z5MHMMLuFUPYtUAapGkl6382TJlZ_n6nuGmkBrsUd5eKThUyAhNUwd0Ydo2BQWLM04Ivg" http://172.17.0.2:30485/financa/cartoes; done
   
   
   
   